# 0 = disabled, 1 = warning, 2 = error
extends: 
  - prettier
  - plugin:import/errors
  - plugin:import/warnings
plugins:
  - import
env:
  browser: true
parserOptions:
  sourceType: 'module'
  ecmaVersion: 2017
settings:
  import/resolver: node
rules:
  indent: [ 2, 'tab', { SwitchCase: 1 } ],
  semi: [ 2, 'always' ],
  keyword-spacing: [ 2, { before: true, after: true } ],
  space-before-blocks: [ 2, 'always' ],
  prefer-arrow-callback: 2
  prefer-const: [ 2, { destructuring: 'all' } ],
  no-this-before-super: 2
  no-var: 2
  no-unreachable: 2
  valid-typeof: 2
  quote-props: [ 2, 'as-needed' ]
  one-var: [ 2, 'never' ]